"use client" ///////////////////////////////////////////////

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Provider } from "react-redux";

import { Header } from "../components/Header/Header";
import { Sidebar } from "../components/Sidebar/Sidebar";
// import { store } from "@/components/utils/redux/store"; old store
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          <div className="container">
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
