"use client" ///////////////////////////////////////////////

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Provider } from "react-redux";

import { Header } from "../components/Header/Header";
import { Sidebar } from "../components/Sidebar/Sidebar";
import { store } from "@/components/utils/redux/store";

const inter = Inter({ subsets: ["latin"] });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Provider store={store}>
          {/* <div className="wrapper"> */}
          <Header />
          <div className="container">
            {children}
            {/* </div> */}
          </div>


        </Provider>
      </body>
    </html>
  );
}
